### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#1254]
This document outlines what features can be expected to change before jade gets to 1.0.0 (i.e. stability).
## For discussion
- [ ] Serialization of data-attributes, should it really do `JSON.stringify` (#1062 #1075)
- [ ] Consider defaults for debug mode (#1098)
## Tasks for post 1.0.0
- [ ] Update documentation
- [ ] Build bot to fix code reliant on deprecated features
- [ ] Add auto-completion plugin for brackets.io
## Future
- [ ] Child templates with contents should throw an error (#870)
- [ ] Better errors for incorrectly named blocks in extending templates (#885)
- [ ] Provide API for exposing dependency graph of jade files for dynamic recompilation (#957)
- [ ] Error when the same block appears multiple times in a file (#1009)
- [ ] Runtime filters so that interpolation is an option, this is up for debate (#1146)
