### ISSUE TITLE
2.0.0 Roadmap

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug#1834]
This is a place-holder issue for the 2.0.0 roadmap.  I currently plan to close all issues that don't absolutely need to be fixed in the v1 branch.  Then release v1.9.2.  At this point, we will have a freeze on v1 features, except additional warnings that can become errors in v2.0.0.  I will then merge the ongoing 2.0.0 work into master.

**Comment by ForbesLindesay** [comment]
The next release will be the final 1.x.x release.  At that point I will merge in the refactoring work and begin working on the 2.0.0 change log.

**Comment by ForbesLindesay** [comment]
I created a branch at https://github.com/jadejs/jade/tree/v1.x.x which can be used for any bug fixes on 1.x.x, but I actively want to discourage working on that branch unless major bugs are discovered because it will ultimately just slow 2.0.0 down.

Tasks to be completed before releasing 2.0.0:

## Fix Ready

The following issues have open pull requests to fix

 - Remove CLI from core (fixready: #1993)
 - Remove pre-built binaries from core (fixready: #1992)

## Testing Required

The following issues may turn out to no longer be problems.  Someone needs to investigate them.

 - [ ] Support first line of pipeless text being indented (#1588)
 - [ ] Ensure that multi-line interpolation reports a helpful error message (#1723)
 - [ ] Check that mis-matched brackets result in the correct error for interpolation (#1871)
 - [ ] Check that we don't have any code using un-guarded for/in loops (#1892)
 - [ ] Check that mixins ignore white space after the call (#1898)
 - [ ] Ensure that line numbers are included in the "no closing bracket found" error (#1922)
 - [ ] Investigate possible mixins bug (#1979)

## Blocking

The following issues must be resolved before 2.0.0 can be released

 - [ ] Fix bug where some tags get recognised as keywords and visa versa (#1750)
 - [ ] Allow users to explicitly specify all globals and not allow implicit globals, resulting in better performance (#1773)
 - [ ] Fix issue with Comma-First + Tabs (#1800) - just needs us to be consistent between tabs and spaces
 - [ ] Treat `-` followed by a newline as an "Empty Statement" (#1916)
 - [ ] Allow umlautes etc. in class names (#1904)
 - [ ] Scan entire AST for doctype before compiling (#1918)
 - [ ] Add space after inline comments (#1942)
 - [ ] Mark textarea as whitespace sensitive (#1931) - this could be ignored if we removed pretty printing

## High Priority

These issues are technically non-breaking changes, so they could be left until after the 2.0.0 release, but it would be a huge win to get them resolved before then.

 - [ ] Force the compiler to generate a new statement every n (where n is somewhere between 10 and 200) concatenations (#1846)
 - [ ] Look for opportunities to catch more errors (#1825)
 - [ ] Support ES6 multi-line strings in attributes (#1969)

## Discussions

We should make a decision about the following issues before releasing 2.0.0

 - [ ] Decide on whether to implement a shorter syntax for `&attributes` (#1744)
 - [ ] Possibly sort attributes for better compression (#1793 and #1914)
 - [ ] Consider supporting a default block in template inheritance (#1902)
 - [ ] Consider supporting `.` that is not attached to a tag (#1939)

## Low Priority

These items are nice to have, but we could leave them.

 - [ ] Break pretty printing into a separate module (#1123)
 - [ ] Document and validate options passed to jade.compile etc. (#1728)

**Comment by TimothyGu** [comment]
Checklist updated for #1997, #1979, #1892, #1969, & #1898, which are all closed for one reason or another.

**Comment by TimothyGu** [comment]
All non-low-priority issues have been solved. \o/

**Comment by ForbesLindesay** [comment]
I've added two more "Blocking" items.  Everything in low priority can be left till the next milestone.

**Comment by ForbesLindesay** [comment]
I've released an initial alpha:

https://www.npmjs.com/package/pug

pug@2.0.0-alpha1

It would be great if as many people as possible could try this out and report any issues they find.

**Comment by alubbe** [comment]
Great release. Works for me, and the performance looks wonderful. We've gotten so much faster :+1:

**Comment by TimothyGu** [comment]
Most of these have been solved.
